apiVersion: v1
kind: Service
metadata:
  name: mqtttosparkplug
  namespace: {{ .Values.tenantNamespace }}
  labels:
    app: mqtttosparkplug
spec:
  ports:
  - port: 80
  selector:
    app: mqtttosparkplug